#!/usr/bin/env python3
"""
Build handbook files by assembling content from across the repository.

Reads the curriculum map, collects principles from core doctrine, and
generates or updates handbook index files.

Usage:
    python scripts/build_handbook.py
    python scripts/build_handbook.py --dry-run
"""

import re
import sys
from datetime import date
from pathlib import Path


ACADEMY_ROOT = Path(__file__).resolve().parent.parent
HANDBOOK_DIR = ACADEMY_ROOT / "handbook"


def parse_curriculum_map():
    path = ACADEMY_ROOT / "CURRICULUM_MAP.md"
    if not path.exists():
        return None

    content = path.read_text(encoding="utf-8")
    tracks = re.findall(
        r"### Track (\d{2}): ([^\n]+)",
        content,
    )
    return {num: name.strip() for num, name in tracks}


def parse_principles():
    path = ACADEMY_ROOT / "01_core_doctrine" / "PRINCIPLES.md"
    if not path.exists():
        return []

    content = path.read_text(encoding="utf-8")
    principles = []
    sections = re.split(r"\n## PRN-", content)
    for section in sections[1:]:
        lines = section.strip().split("\n")
        principle_id = "PRN-" + lines[0].strip()
        title = ""
        claim = ""
        for line in lines[1:]:
            if line.startswith("| **title**"):
                title = line.split("|")[2].strip()
            if line.startswith("| **claim**"):
                claim = line.split("|")[2].strip()
        if claim:
            principles.append({
                "id": principle_id,
                "title": title,
                "claim": claim,
            })
    return principles


def collect_module_contents():
    modules = {}
    module_dirs = [
        "00_orientation",
        "01_core_doctrine",
        "02_principal_plus",
        "03_business_and_gtm",
        "04_product_archetypes",
        "05_ai_product_management",
        "06_industry_overlays",
        "07_cases",
        "08_contradictions",
        "09_tools",
        "10_simulator",
        "11_learning_paths",
        "12_personal_lab",
    ]

    for md_dir in module_dirs:
        dir_path = ACADEMY_ROOT / md_dir
        if not dir_path.is_dir():
            continue
        md_files = sorted(dir_path.glob("*.md"))
        modules[md_dir] = [f.name for f in md_files]

    return modules


def generate_handbook_index(dry_run=False):
    handbook_dir = HANDBOOK_DIR
    if not dry_run:
        handbook_dir.mkdir(parents=True, exist_ok=True)

    tracks = parse_curriculum_map()
    principles = parse_principles()
    modules = collect_module_contents()

    today = date.today().isoformat()

    index_content = f"""# Product Leadership Academy Handbook

*Auto-generated: {today}*

## Overview

This handbook assembles content from across the Product Leadership Academy
into a consolidated reference. It is regenerated by `scripts/build_handbook.py`.

---

## Curriculum Tracks

"""
    if tracks:
        for num, name in sorted(tracks.items()):
            index_content += f"- **Track {num}:** {name}\n"
    else:
        index_content += "*(Curriculum map not found)*\n"

    index_content += f"""
---

## Canonical Principles ({len(principles)} total)

"""
    for p in principles:
        index_content += f"### {p['id']}: {p['title']}\n\n"
        claim = p['claim'][:300]
        if len(p['claim']) > 300:
            claim += "..."
        index_content += f"{claim}\n\n"

    index_content += """
---

## Module Index

"""
    for md_dir in sorted(modules):
        label = md_dir.replace("_", " ").title()
        index_content += f"### {label}\n\n"
        for fname in modules[md_dir]:
            index_content += f"- [{fname}](../{md_dir}/{fname})\n"
        index_content += "\n"

    index_content += f"""
---

*Handbook generated {today} by build_handbook.py. This is a consolidated
reference; canonical content lives in the source directories listed above.*
"""

    output_path = handbook_dir / "HANDBOOK.md"
    if dry_run:
        print(f"[DRY RUN] Would write {output_path}")
        print(f"  Tracks: {len(tracks) if tracks else 0}")
        print(f"  Principles: {len(principles)}")
        print(f"  Module dirs: {len(modules)}")
    else:
        output_path.write_text(index_content, encoding="utf-8")
        print(f"  Written: {output_path}")
        print(f"  Tracks: {len(tracks) if tracks else 0}")
        print(f"  Principles: {len(principles)}")
        print(f"  Module dirs: {len(modules)}")


def main():
    dry_run = "--dry-run" in sys.argv

    print("Building Product Leadership Academy Handbook")
    print(f"Root: {ACADEMY_ROOT}")
    print()

    generate_handbook_index(dry_run=dry_run)

    print()
    print("=" * 60)
    if dry_run:
        print("Dry run complete. Use without --dry-run to write files.")
    else:
        print("Handbook build complete.")


if __name__ == "__main__":
    main()
